# ChatAnnouncer Configuration

# Interval in seconds between each announcement.
# Default is 300 seconds (5 minutes).
interval: 300

# List of messages to be announced.
# Messages will be displayed in the order they are listed.
# - Use '&' for color codes (e.g., &a for green).
# - Use '\n' for a new line within a single message entry.
messages:
  - "&aWelcome to our server! We hope you have a great time."
  - "&eDon't forget to read the /rules."
  - "&bJoin our Discord server!&nhttps://discord.gg/yourinvite"
  - "&dThis is a multiline message.\\n&dThis is the second line."
  - "&cEnjoy your stay!"
